version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/:/etc/nginx/conf.d/
      ports:
          - "8488:80"

    php-fpm:
      build: docker/php-fpm
      container_name: laravel-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    mariadb:
      image: mariadb:10.3
      container_name: laravel-mariadb
      volumes:
        - ./docker/mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: qwerty
      ports:
        - "3306:3306"
